### PR TITLE
Improved reliability of clicking on disclosure triangle

### PR DESCRIPTION
**Pull request by FigBug**
I was still having issues clicking the triangle to open / close items. Now the hit target is the exact location of where the triangle is drawn.

### CODE REVIEW

**Comment by sudara** [comment]
hmm what OS have you been using? Wondering if it was a mac/win issue.

**Comment by FigBug** [comment]
I'm on macOS

**Comment by sudara** [comment]
macOS here too. Strange, I still wonder what the specific issue was, it was very solid for me.

Good call on having a `disclosureRect` and deriving bounds via event translation. Much better than the recursive parent stuff I stole from TreeViewItem.

One thing we lose from my implementation is a bit of extra clickable disclosure to the left of the icon (always nice for UX to have a bit of padding around clickable icons).

This implementation has a couple glitches for me:

1. The item is suddenly selectable in a sliver to the left of the icon.

AudioPluginHost - 2023-08-16 24

2. The right side of the icon behaves as selection vs. disclosure toggle. It should be a toggle right up to the first pixel of text.
 
AudioPluginHost - 2023-08-16 51


Also, this is unrelated to your changes, but there seems to be a debounce glitch when toggling disclosure on non-selected item. 

AudioPluginHost - 2023-08-16 57

**Comment by FigBug** [comment]
Ok, I tweaked the hit test area

**Comment by sudara** [comment]
Pixel perfect! Thanks Roland!!

**Pull request merged**
