### PR TITLE
Modify ci.yml 'on' to run on pull request; Add Linux

### LINKED ISSUE #93: Add Linux to CI matrix
See #92

### PR DESCRIPTION
**Pull request by baconpaul**
Closes #93 

Lets see if this works!

### CODE REVIEW

**Comment by baconpaul** [comment]
There you go! This is now running the CI on a PR

**Comment by baconpaul** [comment]
OK re-pushed to add ubuntu also. Lets see!

**Comment by sudara** [comment]
> This is now running the CI on a PR

To a be a jerk, it probably was going to work anyway, as you were no longer a first time contributor! 

But you are right, pull_request was removed here, maybe due to some annoyance with it firing twice with push sometimes?

> OK re-pushed to add ubuntu also.

letsgooooo, going for gold!!!

**Comment by baconpaul** [comment]
yeah lemme try a bit!

**Comment by sudara** [comment]
i think that error was mentioned here: https://github.com/sudara/melatonin_inspector/issues/93#issuecomment-1735496758

I thiiiink related to the precompiled binary asset stuff — it might a bit of cleanup, but lol, surprise it's managed by `[copy_cmake_assets.rb](https://github.com/sudara/melatonin_inspector/blob/main/copy_cmake_assets.rb)`

**Comment by baconpaul** [comment]
OK looks like that will work. let me squash it and rewrite the comment.

**Comment by baconpaul** [comment]
OK this is ready!

**Comment by baconpaul** [comment]
Oooh actually hold on a second.

**Comment by baconpaul** [comment]
So the precompiled thing. You are treating them as part of your main module whereas juce cmake usually makes them a separate library it compiles itself (with different flags). So it ejects code which doesn't work with error and standard juce warnings. 

That's OK though. You can wrap the inclusion of the CPP in a suppress-that-error GCC block I think and have a change to do that

Add `edgeGap` -> `_edgeGap` in the ctor argument and in theory you can run linux CI with warnings are errors on.

Lets see!

**Comment by baconpaul** [comment]
OK now this is really really good to go! :)

**Review by sudara — APPROVED** [review]
Amazing.

**Pull request merged**
