### PR TITLE
Toggle dragging/resize and toggle "selection lock"

### LINKED ISSUE #49: Add toggle for dragging and resizing components
Figure out a way to disambiguate (defer dragging to the app by default?)

### LINKED ISSUE #90: Selection lock
I need to be able to click around in my UI without losing the component I'm currently looking at. A switch to disable the overlay while keeping the inspector active?

### PR DESCRIPTION
**Pull request by dikadk**
Resolves #49 
Resolves #90

We still need to use real "selection lock" icon, instead of placeholder. But selection/dragging logic is in place. 

https://github.com/sudara/melatonin_inspector/assets/15266737/572395b2-d6f2-4e8d-b9e7-4635b5d42554

### CODE REVIEW

**Comment by sudara** [comment]
Hey, cool! 

Is the goal to solve #49 as well as #90? I got confused by the vid a bit. Would these be the two features:

a) "lock" a selection (current selection is locked in place, another component can't be selected)
b) disable ability to move and resize selected components 

Some thoughts:

* I'm wondering if we should call the latter `readOnly` or something internally, since it's more than dragging, it's also resizing dimensions.
* When dragging/resizing is disabled, should this be consistent and include disabling editing from properties and the box model?

Also I just opened #102 which builds on the `SelectionMode`  enum stuff that Baconpaul added. Not sure it makes sense but we could add a mode called LOCKED?

In it, I basically call `overalyMouseListener.disable()` to disable selection, so maybe we should at least align that stuff a bit!

**Comment by dikadk** [comment]
> Hey, cool!
> 
> Is the goal to solve #49 as well as #90? I got confused by the vid a bit. Would these be the two features:
> 
> a) "lock" a selection (current selection is locked in place, another component can't be selected) b) disable ability to move and resize selected components
> 
> Some thoughts:
> 
> * I'm wondering if we should call the latter `readOnly` or something internally, since it's more than dragging, it's also resizing dimensions.
> * When dragging/resizing is disabled, should this be consistent and include disabling editing from properties and the box model?
> 
> Also I just opened #102 which builds on the `SelectionMode` enum stuff that Baconpaul added. Not sure it makes sense but we could add a mode called LOCKED?
> 
> In it, I basically call `overlayMouseListener.disable()` to disable selection, so maybe we should at least align that stuff a bit!

Yes, this PR covers both https://github.com/sudara/melatonin_inspector/issues/49 and https://github.com/sudara/melatonin_inspector/issues/90

a) exactly how 'lock' works in this PR. Need a new icon for this.
b) I think I only handled drag... will check resize as well

'readOnly' - makes more sense, since I missed resize. Totally make sense. 
I think I can disable properties and box model, didn't even think of that. I was focused on keeping selection and controls other component. 😊 

Yeah, that would be nice! We're starting to have to many bool flags. I'll take a look at SelectionModes

**Comment by sudara** [comment]
> I'll take a look at SelectionModes

Yeah, not 100% sure it makes sense, just thought I'd mention. To do that, we'd need to have the UI be a multi-select (mouse vs. tab vs. locked??).

> Need a new icon for this.

I can get on that. I was originally thinking it would be nice to see a lock icon in the tree view... i guess we could actually make the toggle there (like a lock action button would show up when you hovered over an item) — but maybe it's just more straightforward to have it in the header and maybe bound to `L` key or something.

**Comment by sudara** [comment]
@dikadk Should I take a look at this and add a lock toggle? Or is there more you wanted to do on it...

**Comment by dikadk** [comment]
> @dikadk Should I take a look at this and add a lock toggle? Or is there more you wanted to do on it...

I looked into adding Locked - SelectionMode, but it wasn't quite fitting. It was turning into making more changes. 
I've updated 'resizing' logic to only work with focus mode and automatically switch. Short demo attached. 

https://github.com/sudara/melatonin_inspector/assets/15266737/54b6dda3-6a68-4ce3-8000-45d5a1c2e821

**Comment by sudara** [comment]
Hey cool!

No worries on the SelectionModes, just wanted to mention them since they are new.

Wait, I got confused again. Does this PR cover #60? I'm guessing the answer is no and I can still click to select other components when dragging is disabled. That's 100% fine if true — and actually ideal? I guess we'd want the selection lock to be a different toggle I think...

**Comment by dikadk** [comment]
Just updated PR title. Sorry for confusion.

This one ONLY covers dragging and resizing functionality in FOLLOW_FOCUS SelectionMode. I found it kinda clunky in FOLLOW_FOCUS mode. 

Maybe we can add another btn for LOCKING selection? Get a 'lock' icon and I can open another PR for that.

**Comment by sudara** [comment]
Ok perfect! I'll check it out asap and merge and figure out a lock icon while I'm at it...

**Comment by sudara** [comment]
I added the lock icon, did a bit of refactoring and then just decided to add the lock. It's very basic right now, just prevents any selection or hover. Not sure if we want to hover on lock?...

**Pull request merged**
