### PR TITLE
Release v1.3: Color, Properties and Component Timings

### LINKED ISSUE #22: Show which component has keyboard focus in tree view
Right now we show "wantsKeyboard" in the tree view 

Until emoji support hits JUCE 7.x (which would let us use ⌨️), it would be nice to highlight which component has keyboard focus somehow.

### LINKED ISSUE #33: Remember panel open/close state across usages

### LINKED ISSUE #34: FR: Add Magnifying Glass to Color Picker to make it easier to inspect colors
image

### PR DESCRIPTION
**Pull request by sudara**
This builds upon @FigBug's property and color work in #46 and:

* [x] Puts the treeview on the left (let's see if it feels more right!)
* [x] Closes #34
* [x] Closes #33
* [x] Closes #22 
* [x] Uses custom mouse cursor for eyedropper
* [x] Puts color properties in the color panel
* [x] Add switch for rgba <-> hex color display
* [x] Wrote a ruby script that scrapes for enum ColourIDs to let us display JUCE's ColourIDs by enum name 
* [x] Uses the existing color picker UI for property UI
* [x] Turning the color picker disables the overlay 
* [x] Clicking to pick a color turns the color picker off and reenables the overlay
* [x] Shows last picked color
* [x] When color panel is closed, the color picker should be disabled
* [x] Basic theming of the JUCE color swatches popup
* [x] Puts custom properties on top of prop panel and uses the highlight color to call them out (would prefer a "tag" here, but would require breaking out of the property component)
* [x] Removes the ability to pass in a properties file, instead stores settings in a SharedResourcePointer so it can be accessed from any component
* [x] Formats an `int64` property ending in `At` (such as `lastPaintAt` as a time (open to suggestions/improvement)
* [x] Adds `propertiesToIgnore` for special properties used elsewhere in the UI (padding, timing) with the intention that this can be user configurable in the future
* [x] Unify `melatonin::colors` formats and names
* [x] Clean up scrollbar to match Figma colors and work around JUCE's brittletree view implementation
* [x] Add "max" to paint timings
* [x] Double clicking the preview panel repaints the selected component, clears the MAX timing 
* [x] Add RAII helper to collect paint timings

TODO:

* [x] Final UI cleanup up of color panel
* [x] Fix keyboard focus icon on root
* [x] Fix timings still shown on components without timing 
* [x] Fix preview sometimes not repainted/updated (for example waveform on sine machine)
* [x] Fix fiddley disclosure triangle issue

FOLLOWUPS:

* [ ] Keyboard focus improvements (track lastFocused, deal with wantsKeyboardFocus)
* [ ] The preview<->color picker relationship is a bit sketchy
* [ ] Passing in a callback to the picker that calls a callback is a dubious amount of indirection
* [ ] Clean up property adding in the model, it's become spaghetti...
* [ ] Clean up / align fonts

AudioPluginHost - 2023-08-14 38

AudioPluginHost - 2023-08-14 25

AudioPluginHost - 2023-08-14 01

AudioPluginHost - 2023-08-16 57

### CODE REVIEW

**Comment by sudara** [comment]
@dikadk This is just about ready to go, you could include `melatonin_inspector/melatonin/helpers/timing.h`
stick `melatonin::ComponentTimer timer { this };` at the top of a paint method to try it out. 

Still a few bugs to knock out, then I'll update README and announce the features on the forum.

**Comment by sudara** [comment]
Ok, I fixed all the bugs I kept running into. If anyone wants to test before release, I'd be happy!

**Comment by FigBug** [comment]
Here is a patch that cleans up some warnings. Also, when disabling the colour picker, I think the zoomed in image should go back to the zoomed out version.

[warnings.patch](https://github.com/sudara/melatonin_inspector/files/12353456/warnings.patch)

**Comment by sudara** [comment]
Thanks!

> when disabling the colour picker, I think the zoomed in image should go back to the zoomed out version.

Ah yeah, I feel like i fixed this 5 times, I'll do another round, thx!

**Comment by FigBug** [comment]
Another issue I'm seeing is clicking on an item in the tree either expands it or collapses it, but does not always select it. Seems like you can only reliably select items without children.

**Comment by sudara** [comment]
> does not always select it.

@FigBug Is this *only* in the case of clicking on the disclosure triangle (or to the left of it)? If so that was intentional, to allow open/closing without changing selection. But if you think it makes most sense to always select on open, I can add that behavior back. Also let me know if you are seeing it be glitchy, as I spent (too much time) trying to sort that, it's possible there's still some edge cases.

It looks like on deselect the preview needs to be cleared too. I'll take a look tomorrow.

**Comment by sudara** [comment]
Ahh, found the issue. It was really next to impossible to skin the TreeViewItem as we had it designed (full width background selection), as the the widget's styling/position is coupled with behavior (as JUCE widgets). The issue here was twofold, toggling disclosure was forcing selection and I accidentally left in some additional mouse listening.

I double checked the existing behavior on `main`:

* Clicking to the left of a disclosure icon (in the empty space) does nothing
* Clicking a disclosure icon expands/collapses, but never selects or deselects
* Clicking the text (or to the right of the text) always selects AND opens or deselects (leaving it open) without closing.

AudioPluginHost - 2023-08-16 38

Behavior should now be same as on main main. 

However, there are a few minor additional changes:

* Clicking slightly to the left of a disclosure will expand/collapse the disclosure (on main it does nothing)
* Now that the tree is on the left and the "selected" background now goes all the way to the left (as designed) there might be the impression clicking the left gutter should select an item (it could? we could restrict the disclosure behavior to the icon itself)

**Comment by sudara** [comment]
Releasing for now, we can followup with any minor changes.

**Comment by sudara** [comment]
FYI also working on the bug with the color picker and "even number of zoomed in pixels" in case anyone runs into that.

**Pull request merged**
